name: pre-merge check

on: 
  push:
    branches:
    - master
    - develop
    - features/sprint*
    - stable_v*
  pull_request:
    branches:
    - master
    - develop
    - features/sprint*
    - stable_v*

jobs:
  rust-test:
    name: rust test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-20.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1.0.1
        name: build
        with:
          command: build
      - uses: actions-rs/cargo@v1.0.1
        name: test
        with:
          command: test
